developmentMode: false
js:
    minify: true
    sourceMaps: false
css:
    minify: true
    sourceMaps: false
    minifyOptions:
        # Uncomment the below options if minifying the CSS breaks shit
        #compatibility: "ie7, -units.ch, -units.in -units.pc -units.pt -units.rem -units.vh -units.vm -units.vmax -units.vmin"
        #advanced: false
        #aggressiveMerging: false
        #restructuring: false
        #keepSpecialComments: 0
browsersync:
    title: "Project Name"
    proxy: "localhost"
    open: false
    browser: "google chrome"
